#!/usr/bin/env bash
# gen-codex-home.sh — provision a per-agent CODEX_HOME for a bridged Codex agent.
#
# Mirrors ~/.wire/codex-launch.sh policy (isolated config.toml, persistent MCP
# entries so tool_search indexes them, tsx not bun, auth.json symlink) with the
# bridge-specific differences:
#   - NO 'wire' MCP: the codex-wire-bridge owns this agent's inbound SSE; a
#     second SSE under the same id recreates the dual-connection duel
#     (2026-06-10, Brioche's session).
#   - GITHUB_APP_TOKEN_CMD instead of a static GITHUB_TOKEN: installation
#     tokens expire in ~1h; github-tools v1.8.0+ mints on demand.
#   - Linear MCP included (palmier friction list, ENG-3330 wrap-up).
#
# Usage: AGENT_ID=<id> AGENT_PRIVATE_KEY=<pkcs8-b64> [WIRE_URL=...] \
#        [GH_APP_TOKEN_CMD=...] [LINEAR_MCP_URL=...] gen-codex-home.sh
# Prints the CODEX_HOME path on stdout.
set -euo pipefail

: "${AGENT_ID:?AGENT_ID required}"
: "${AGENT_PRIVATE_KEY:?AGENT_PRIVATE_KEY required}"
WIRE_URL="${WIRE_URL:-http://localhost:9800}"
AGITERRA_REPOS="${AGITERRA_REPOS:-/Users/tim/Projects/Agiterra}"
GH_APP_TOKEN_CMD="${GH_APP_TOKEN_CMD:-bash /Users/tim/Projects/Fabrica/fabrica-v3/.claude/scripts/gh-app-token.sh}"
LINEAR_MCP_URL="${LINEAR_MCP_URL:-https://mcp.linear.app/mcp}"

SPAWN_HOME="${HOME}/.wire/codex-spawn/${AGENT_ID}"
mkdir -p "$SPAWN_HOME"
ln -sfn "${HOME}/.codex/auth.json" "${SPAWN_HOME}/auth.json"

cat > "${SPAWN_HOME}/config.toml" <<EOF
# Auto-generated by codex-wire-bridge/scripts/gen-codex-home.sh for AGENT_ID=${AGENT_ID}.
# Hand-edits will be overwritten on next generation.
# 'wire' MCP deliberately OMITTED — the bridge owns inbound (see script header).

model = "gpt-5.5"
model_reasoning_effort = "${MODEL_REASONING_EFFORT:-high}"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[features]
rmcp_client = true

[mcp_servers.wire-ipc]
command = "tsx"
args = ["${AGITERRA_REPOS}/wire-ipc-codex/server.ts"]
startup_timeout_sec = 30

[mcp_servers.wire-ipc.env]
AGENT_ID = "${AGENT_ID}"
AGENT_NAME = "${AGENT_NAME:-$AGENT_ID}"
AGENT_PRIVATE_KEY = "${AGENT_PRIVATE_KEY}"
WIRE_URL = "${WIRE_URL}"

[mcp_servers.agiterra-github]
command = "tsx"
args = ["${AGITERRA_REPOS}/github-codex/server.ts"]
startup_timeout_sec = 30

[mcp_servers.agiterra-github.env]
AGENT_ID = "${AGENT_ID}"
AGENT_PRIVATE_KEY = "${AGENT_PRIVATE_KEY}"
GITHUB_APP_TOKEN_CMD = "${GH_APP_TOKEN_CMD}"
WIRE_URL = "${WIRE_URL}"

[mcp_servers.linear]
url = "${LINEAR_MCP_URL}"
EOF
chmod 600 "${SPAWN_HOME}/config.toml"
echo "$SPAWN_HOME"
