#!/usr/bin/env bash
# gen-codex-home.sh — provision a per-agent CODEX_HOME for a bridged Codex agent.
#
# Mirrors ~/.wire/codex-launch.sh policy (isolated config.toml, persistent MCP
# entries so tool_search indexes them, tsx not bun, auth.json symlink) with the
# wire-codex specifics:
#   - the 'wire' MCP (set_plan/heartbeat/register) is served over StreamableHTTP
#     by THIS agent's wire-codex injector and reached by URL — config.toml gets
#     [mcp_servers.wire] url=http://127.0.0.1:$WIRE_MCP_PORT/mcp. It shares the
#     injector's SINGLE Wire connection (no second SSE — the old dual-connection
#     duel is gone), and inbound still arrives as app-server turn injection.
#     Appended only when WIRE_MCP_PORT is set.
#   - GITHUB_APP_TOKEN_CMD instead of a static GITHUB_TOKEN: installation
#     tokens expire in ~1h; github-tools v1.8.0+ mints on demand.
#   - Linear MCP included (palmier friction list, ENG-3330 wrap-up).
#
# Usage: AGENT_ID=<id> AGENT_PRIVATE_KEY=<pkcs8-b64> [WIRE_URL=...] \
#        [WIRE_MCP_PORT=<port>] [GH_APP_TOKEN_CMD=...] [LINEAR_MCP_URL=...] gen-codex-home.sh
# Prints the CODEX_HOME path on stdout.
set -euo pipefail

: "${AGENT_ID:?AGENT_ID required}"
: "${AGENT_PRIVATE_KEY:?AGENT_PRIVATE_KEY required}"
WIRE_URL="${WIRE_URL:-http://localhost:9800}"
AGITERRA_REPOS="${AGITERRA_REPOS:-/Users/tim/Projects/Agiterra}"
GH_APP_TOKEN_CMD="${GH_APP_TOKEN_CMD:-bash /Users/tim/Projects/Fabrica/fabrica-v3/.claude/scripts/gh-app-token.sh}"
LINEAR_MCP_URL="${LINEAR_MCP_URL:-https://mcp.linear.app/mcp}"

SPAWN_HOME="${HOME}/.wire/codex-spawn/${AGENT_ID}"
mkdir -p "$SPAWN_HOME"
ln -sfn "${HOME}/.codex/auth.json" "${SPAWN_HOME}/auth.json"

cat > "${SPAWN_HOME}/config.toml" <<EOF
# Auto-generated by wire-codex/scripts/gen-codex-home.sh for AGENT_ID=${AGENT_ID}.
# Hand-edits will be overwritten on next generation.
# The 'wire' MCP is served over HTTP by the wire-codex injector (appended below
# when WIRE_MCP_PORT is set); inbound arrives as turn injection, not via the MCP.

model = "gpt-5.5"
model_reasoning_effort = "${MODEL_REASONING_EFFORT:-high}"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[features]
rmcp_client = true

[mcp_servers.wire-ipc]
command = "tsx"
args = ["${AGITERRA_REPOS}/wire-ipc-codex/server.ts"]
startup_timeout_sec = 30

[mcp_servers.wire-ipc.env]
AGENT_ID = "${AGENT_ID}"
AGENT_NAME = "${AGENT_NAME:-$AGENT_ID}"
AGENT_PRIVATE_KEY = "${AGENT_PRIVATE_KEY}"
WIRE_URL = "${WIRE_URL}"

[mcp_servers.agiterra-github]
command = "tsx"
args = ["${AGITERRA_REPOS}/github-codex/server.ts"]
startup_timeout_sec = 30

[mcp_servers.agiterra-github.env]
AGENT_ID = "${AGENT_ID}"
AGENT_PRIVATE_KEY = "${AGENT_PRIVATE_KEY}"
GITHUB_APP_TOKEN_CMD = "${GH_APP_TOKEN_CMD}"
WIRE_URL = "${WIRE_URL}"

[mcp_servers.linear]
url = "${LINEAR_MCP_URL}"
EOF

# The agent's own 'wire' MCP — served over StreamableHTTP by its wire-codex
# injector on $WIRE_MCP_PORT, sharing the injector's single Wire connection.
if [ -n "${WIRE_MCP_PORT:-}" ]; then
  cat >> "${SPAWN_HOME}/config.toml" <<EOF

[mcp_servers.wire]
url = "http://127.0.0.1:${WIRE_MCP_PORT}/mcp"
EOF
fi
chmod 600 "${SPAWN_HOME}/config.toml"
echo "$SPAWN_HOME"
